### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by kanekotic** [CodeInBrackets/wind.js#1]
![logomakr_01gz5x](https://user-images.githubusercontent.com/3071208/38959874-9addaa8e-4362-11e8-9904-38fba6503ae2.png)

**Comment by kmruiz** [comment]
![actor](https://user-images.githubusercontent.com/1822138/39409821-faed94f0-4bed-11e8-8c05-3741d7fbb322.png)

**Comment by kmruiz** [comment]
![lifecycle](https://user-images.githubusercontent.com/1822138/39409919-1d49c2b6-4bef-11e8-8016-78650cd9d326.png)

**Comment by kanekotic** [comment]
![logomakr_8cwvt1](https://user-images.githubusercontent.com/3071208/42311453-254a1474-803e-11e8-957a-5c1c8d157b31.png)

**Comment by kanekotic** [comment]
![logo](https://user-images.githubusercontent.com/3071208/50427407-f0be3c00-086c-11e9-93a0-2acba97d3d28.png)
![logomakr_7yenvo](https://user-images.githubusercontent.com/3071208/50427408-f7e54a00-086c-11e9-8fb6-43506ad4d454.png)
